updated the CI/CD to validate the api endpoint file

diff --git a/.github/workflows/validate-repository-structure.yml b/.github/workflows/validate-repository-structure.yml
--- a/.github/workflows/validate-repository-structure.yml
+++ b/.github/workflows/validate-repository-structure.yml
@@ -21,4 +21,20 @@ jobs:
 
           echo "docs folder exists."
 
+      - name: Check required documents
+          if [ ! -f "docs/race_day_erd.pdf" ]; then
+            echo "ERROR: race_day_erd.pdf is missing."
+            exit 1
+          fi
+
+          echo "All required documents are present."
+
+          if [ ! -f "docs/race_day_api_endpoints.pdf" ]; then
+            echo "ERROR: race_day_api_endpoints.pdf is missing."
+            exit 1
+          fi
+
+                - name: Validate repository structure
+        run: |
+          echo "Repository structure is valid."
       
